name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What were you expecting?
      placeholder: Describe what you see.
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System?
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Plugin version?
      options:
        - 1.0.0
      default: 0
    validations:
      required: true
