name: Style Request
description: Request a new reference style
title: "[Style]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this style request!
  - type: textarea
    id: other
    attributes:
      label: Anything else to add?
      placeholder: This can be left blank if it's self explanatory.
    validations:
      required: false
