name: Update issue template versions

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3

        - name: Update bug report template
          run: |
            sed -i "/- 1.0.0/ s/$/\\n        - ${{ github.event.release.tag_name }}/" .github/ISSUE_TEMPLATE/bug_report.yaml
        
        - name: Commit and push changes
          run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add .github/ISSUE_TEMPLATE/bug_report.yaml
            git commit -m "Update version options in bug report template"
            git push origin main
